### ISSUE TITLE
Subscriptions in abstract classes aren't killed if concrete component doesn't have decorator, but has its own OnDestroy implementation

### ISSUE THREAD

**Issue by WetCouch** [ngneat/until-destroy#175]
If abstract class utilizes `untilDestroyed`, the subscriptions will be left hanging if the concrete component doesn't have `@UntilDestroy` decorator, and at the same time has its own `OnDestroy` implementation.

How to reproduce:

```ts
@UntilDestroy()
@Directive()
abstract class AbstractComponent {
    constructor() {
        someSubject
            .pipe(untilDestroyed(this))
            .subscribe();
    }
}


@Component()
class ConcreteComponent extends AbstractComponent implements OnDestroy {
    public ngOnDestroy() {
        someLogic();
    }
}
```

In this scenario, the subscription to `someSubject` won't be killed on destroy of `ConcreteComponent`, and no error related to the lack of decorator would be thrown. You also can't use `super.ngOnDestroy()` within it, as the `AbstractComponent` doesn't have its own `ngOnDestroy` implementation.

The temporary solution would be to add the decorator to all of the concrete classes as well, however, it's fairly easy to forget about it without any kind of warning.

**Comment by WetCouch** [comment]
@Rush Unfortunately, as described above, `super.ngOnDestroy()` is not available within the concrete component unless manually added to the abstract - the decorator is not enough for that, so provided solution would need adding an empty `ngOnDestroy` implementation to the abstract.

**Comment by arturovt** [comment]
Hey @WetCouch . Sorry for the delay, I'm going through hard times in Ukraine. I've checked your example locally and it really doesn't unsubscribe. I've tried multiple ways to fix it but haven't found any approach for this particular case...

**Comment by arturovt** [comment]
Hey @WetCouch . Since there's no way to fix that issue internally, I've decided to add a checker which checks if the subject still has observers or not once the view is removed (https://github.com/ngneat/until-destroy/commit/93199cfbb7cd01c72fc8f0531c81c15ae2baef50).

Firstly I was seeking a way to intercept class inheritance through Proxy. Unfortunately, it doesn't have that functionality.

The checker retrieves an `lView` (logical view) when the view is created and setups a function which will be called once the view is destroyed (similarly to `ComponentRef.onDestroy`). It then retrieves a subject and checks if it has observers in a microtask (promise), and logs a warning to the console.

I'm closing an issue, but feel free to re-open if you encounter any issues again.

**Comment by arturovt** [comment]
I'm re-opening the issue. As proposed by Netanel I'll work on the ESLint rule.

**Comment by arturovt** [comment]
After a bit of investigation, I've found out that the ESLint rule is not the best solution. The AST is collected per file, and there's no way to know if the class extends some base class which is decorated or not because the base class may be imported from another file.

My initial mistake was trying to touch the `UntilDestroy` decorator and returning a new class, where I forgot about JIT and AOT modes incompatibility. The new class basically broke metadata collection for JIT mode.

I was thinking if we're able to do the same setup within `untilDestroyed` (since we pass `this` as the first argument):
```ts
const CLEANUP = 7;
function setupCleanup(instance: any, symbol: symbol) {
  Promise.resolve().then(() => {
    const lView: NonNullable<ReturnType<typeof ɵgetLContext>>['lView'] =
      instance.__ngContext__;

    if (lView == null) {
      return;
    }

    const lCleanup = lView[CLEANUP] || (lView[CLEANUP] = []);
    lCleanup.push(() => {
      const destroy$ = instance[symbol];
      Promise.resolve().then(() => {
        if (destroy$.observed) {
          console.warn('Still observed...');
        }
      });
    });
  });
}

export function untilDestroyed<T>(instance: T, destroyMethodName?: keyof T) {
  return <U>(source: Observable<U>) => {
    const symbol = getSymbol<T>(destroyMethodName);

    ngDevMode && setupCleanup(instance, symbol);

    return source.pipe(takeUntil<U>((instance as any)[symbol]));
  };
}
```

cc @NetanelBasal

**Comment by NetanelBasal** [comment]
I'm ok with this solution as long as we have tests for both JIT and AOT.
