### ISSUE TITLE
Expose __destroy Subject

### ISSUE THREAD

**Issue by BojanKogoj** [ngneat/until-destroy#176]
Could it be possible to expose `Symbol(__destroy)` `Subject`?

In our project we have some service which subscribes to a form, but we need to manually emit when to unsubscribe. Since we already use this library I tried to use its logic to help me with that.

I created this function that does the job

```ts
export const destroying = (instance: any): Observable<void> => {
  const key = Reflect.ownKeys(instance).find((key) => key.toString() === 'Symbol(__destroy)');

  return instance[key].asObservable();
};
```

There are two problems with this:
 - I am relying on library internals not to change
 - It's possible to change name using `destroyMethodName`?
 - Doesn't work without using `untilDestroyed(this)` (doesn't add property to component)

Would it make sense to expose it?

**Comment by arturovt** [comment]
Hey @BojanKogoj . I don’t think it makes sense for libraries to expose internal stuff for specific use cases. Also, considering what you’ve described, I’m afraid that you may rely on the subject that doesn’t exist, I mean that subject can be changed, see “internals.ts”, where subject is assigned to null.

We could both think of a better API for that case so that would be public and would be understandable by end users.

I see the function that you’ve provided, could you show me some examples what are you doing and what are you solving? I do understand code better 😄

**Comment by BojanKogoj** [comment]
In component we call
```ts
this.foo.track(this.form.controls, destroying(this));
```
Foo being a service

```ts
track(controls, unsubscribe$: Observable<void>) {
  for (const key of Object.keys(controls)) {
    const control = controls[key];

    control.valueChanges.pipe(takeUntil(unsubscribe$)).subscribe((value) => {
      ...
    });
  }
}
```
Something similar to the above, there is a subscription to observable, that needs to be cleaned when destroying component with the form.

**Comment by arturovt** [comment]
I’ve just checked the above example in the code and it works.

**Comment by BojanKogoj** [comment]
Yes, this should be fine.
