### ISSUE TITLE
Decorator Performance

### ISSUE THREAD

**Issue by alexandercarls** [ngneat/until-destroy#75]
Igor Minar tweeted the following a couple of weeks ago:

> We strip only Angular metadata and decorators. That being said, we **strongly** discourage use of other custom decorators in Angular apps because they almost always cause payload deoptimizations and unused code retention (bigger bundles).

https://twitter.com/IgorMinar/status/1231026653385461760

Is performance a concern for this kind of usage?

**Comment by arturovt** [comment]
What exactly is meant by _performance_?

**Comment by alexandercarls** [comment]
I am sorry I have no further context other the tweet from the Angular project lead who discourage the usage. I don't have the knowledge to judge whether this applies here or not.

I do agree with being pragmatic. The intend was also to raise a potential issue which wasn't thought about.

**Comment by arturovt** [comment]
I've just read [attached link](https://docs.google.com/document/d/1GMp938qlmJlGkBZp6AerL-ewL1MWUDU8QzHBiNvs3MM/edit) to that tweet. Basically, they're unrelated things. V8 team is talking about decorators that can be parsed, compiled and executed at runtime (`decorator @myCustomDecorator { ... }`).

I cannot talk about other libraries since I don't know implementations of all decorators provided by some NPM packages :smile: .

But what the `UntilDestroy` decorator does is only overrides the `onDestroy` property on the directive/component definition, which does the monomorphic property access on the object with the same shape. If we would add a custom property on the definition then yes - it would require the compiler to deoptimize, created another inline cache and new object shape.

**Comment by alexandercarls** [comment]
Sounds reasonable. I am closing the issue :). Thank you!
